name: security-scans

on:
 push:

 workflow_dispatch:

jobs:
  Semgrep:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     security-events: write
     
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
    
      - name: Install semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: run semgrep
        run: |
          semgrep \
            --config=auto \
            --config=security/semgreprules.yml \
            --severity=ERROR \
            --sarif \
            --output=semgrep.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif

      - name: Fail build if Semgrep found issues
        run: |
            grep -q '"level": "error"' semgrep.sarif && exit 1 || exit 0
      

  CodeQL-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
      
    steps: 
      - name: checkout code
        uses: actions/checkout@v6.0.2
        
      - name: Initialize CodeQL-scan
        uses: github/codeql-action/init@v4
        with:
          languages: csharp, javascript
          
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v4

  SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up SonarQube
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          token: ${{ secrets.SONAR_TOKEN }}
  
      - name: Run SonarQube Analysis
        run: |
          # For .NET projects
          dotnet sonarscanner begin /k:"richadevops" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          # For Angular projects
          sonar-scanner -Dsonar.projectKey="richadevops" -Dsonar.sources=src -Dsonar.login="${{ secrets.SONAR_TOKEN }}"


          
