name: security-scans

on:
 push:

 workflow_dispatch:

jobs:
  Semgrep:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     security-events: write
     
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
    
      - name: Install semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: run semgrep
        run: |
          semgrep \
            --config=auto \
            --config=security/semgreprules.yml \
            --severity=ERROR \
            --sarif \
            --output=semgrep.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif

      - name: Fail build if Semgrep found issues
        run: |
            grep -q '"level": "error"' semgrep.sarif && exit 1 || exit 0
      

  CodeQL-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
      
    steps: 
      - name: checkout code
        uses: actions/checkout@v6.0.2
        
      - name: Initialize CodeQL-scan
        uses: github/codeql-action/init@v4
        with:
          languages: csharp, javascript
          
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v4

  SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 9.0.x

      - name: Install frontend dependencies
        run: |
         cd client
         npm install

      - name: Run Angular tests with coverage
        run: |
          cd client
          npm test -- --watch=false --code-coverage

      - name: Run .NET tests with coverage
        run: |
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/ \
            /p:CoverletOutputFormat=opencover

      - name: Set up SonarQube
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=richadevops_DatingApp
            -Dsonar.organization=richadevops
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
            -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            TestResults/
            client/coverage/
