name: security-scans

on:
 push:

 workflow_dispatch:

jobs:
  Semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
    
      - name: Install semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: run semgrep
        run: |
          semgrep \
            --config=auto \
            --config=security/semgreprules.yml \
            --severity=ERROR \
            --error

  CodeQL-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
      
    steps: 
      - name: checkout code
        uses: actions/checkout@v6.0.2
        
      - name: Initialize CodeQL-scan
        uses: github/codeql-action/init@v4
        with:
          languages: csharp, javascript
          
      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v4


  
